#:schema node_modules/wrangler/config-schema.json
name = "test-worker"
main = "index.ts"
compatibility_date = "2024-06-14"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

# Enabling smart placement will automatically place your workloads in an optimal location to minimize latency.
[placement]
mode = "smart"

# [[d1_databases]]
# binding = "MY_DB"
# database_name = "my-database"
# database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
