[update]
tasks = ["interfaces", "code", "transform", "translate", "normalize"]

[update.interfaces]
paths = ["TrollFools"]
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs", "packages", ".theos", ".cache"]
defaultToBase = false
ignoreEmptyStrings = false
unstripped = false
ignoreKeys = ["#bartycrouch-ignore!", "#bc-ignore!", "#i!"]

[update.code]
codePaths = ["TrollFools"]
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs", "packages", ".theos", ".cache"]
localizablePaths = ["TrollFools"]
defaultToKeys = false
additive = true
customFunction = "LocalizedStringResource"
unstripped = false
plistArguments = true
ignoreKeys = ["#bartycrouch-ignore!", "#bc-ignore!", "#i!"]
overrideComments = false

[update.transform]
codePaths = ["TrollFools"]
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs", "packages", ".theos", ".cache"]
localizablePaths = ["TrollFools"]
transformer = "foundation"
supportedLanguageEnumPath = "."
typeName = "BartyCrouch"
translateMethodName = "translate"
separateWithEmptyLine = true

[update.translate]
paths = ["TrollFools"]
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs", "packages", ".theos", ".cache"]
translator = "deepL"
secret = "fec26251-6db0-4d44-b1e1-687930db9258:fx"
sourceLocale = "en"

[update.normalize]
paths = ["TrollFools"]
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs", "packages", ".theos", ".cache"]
sourceLocale = "en"
harmonizeWithSource = true
sortByKeys = true
separateWithEmptyLine = true

[lint]
paths = ["TrollFools"]
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs", "packages", ".theos", ".cache"]
duplicateKeys = true
emptyValues = true
