version: '3.1'

services:
  db:
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=tasks
      - POSTGRES_PASSWORD=admin
    ports:
      - "8848:5432"
