version: "3"
services:
  funasr_interview:
    image: registry.cn-hangzhou.aliyuncs.com/funasr_repo/funasr:funasr-runtime-sdk-online-cpu-0.1.10
    container_name: funasr_interview # 这里是容器名称
    ports:
      - "10096:10095"
    volumes:
      - ./funasr-runtime-resources/models_interview:/workspace/models
    privileged: true
    stdin_open: true
    tty: true
  funasr_rookie:
    image: registry.cn-hangzhou.aliyuncs.com/funasr_repo/funasr:funasr-runtime-sdk-online-cpu-0.1.10
    container_name: funasr_rookie # 这里是容器名称
    ports:
      - "10097:10095"
    volumes:
      - ./funasr-runtime-resources/models_rookie:/workspace/models
    privileged: true
    stdin_open: true
    tty: true
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - redis_network
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis_data:
    driver: local

networks:
  redis_network:
    driver: bridge
