os:
  - Visual Studio 2022

platform: x64

branches:
  only:
    - master

install:
  - git submodule update --init --recursive
  - set PATH=C:\Program Files\CMake\bin;%PATH%

build:
  verbosity: detailed
  
configuration:
  - Release
   
before_build:
  - mkdir build
  - cd build
  - cmake .. -A x64
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=%APPVEYOR_BUILD_FOLDER%/%APPVEYOR_REPO_COMMIT% ..
  
build_script:
  - cmake --build . --config %CONFIGURATION% --target install 
